version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
      - ./IAM_Knowledge:/app/IAM_Knowledge
    environment:
      - PYTHONPATH=/app
      - IAM_RESULTS_BASE=/app/IAM_Knowledge
      - DATABASE_URL=postgresql://iam2:iam2pass@postgres:5432/iam2_dev
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    command: uvicorn iam.backend.app:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./IAM_GUI/static:/usr/share/nginx/html/static
      - ./public:/usr/share/nginx/html/public
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=iam2_dev
      - POSTGRES_USER=iam2
      - POSTGRES_PASSWORD=iam2pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iam2 -d iam2_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app/backend
      - ./IAM_Knowledge:/app/IAM_Knowledge
    environment:
      - PYTHONPATH=/app
      - IAM_RESULTS_BASE=/app/IAM_Knowledge
      - DATABASE_URL=postgresql://iam2:iam2pass@postgres:5432/iam2_dev
      - REDIS_URL=redis://redis:6379/0
      - LOG_LEVEL=DEBUG
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    command: python -m backend.worker
    restart: unless-stopped

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app/backend
      - ./tests:/app/tests
      - ./docs:/app/docs
      - ./IAM_Knowledge:/app/IAM_Knowledge
    environment:
      - PYTHONPATH=/app
      - IAM_RESULTS_BASE=/app/IAM_Knowledge
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    profiles: ["jupyter"]

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: iam2_dev_network
