### Ketcher to SMILES - Success Case
POST http://localhost:8010/ketcher/to-smiles
Content-Type: application/json

{
  "molfile": "\n  Methane\n\n  5  4  0  0  0  0  0  0  0  0999 V2000\n    0.0000    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0\n    0.6291    0.6291    0.6291 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.6291   -0.6291    0.6291 H   0  0  0  0  0  0  0  0  0  0  0  0\n    0.6291   -0.6291   -0.6291 H   0  0  0  0  0  0  0  0  0  0  0  0\n   -0.6291    0.6291   -0.6291 H   0  0  0  0  0  0  0  0  0  0  0  0\n  1  2  1  0  0  0  0\n  1  3  1  0  0  0  0\n  1  4  1  0  0  0  0\n  1  5  1  0  0  0  0\nM  END\n"
}

### Ketcher to SMILES - Error Case (missing field)
POST http://localhost:8010/ketcher/to-smiles
Content-Type: application/json

{
  "invalid_field": "test"
}

### Ketcher to SMILES - Error Case (invalid molfile)
POST http://localhost:8010/ketcher/to-smiles
Content-Type: application/json

{
  "molfile": "invalid structure"
}
